Build updates (#501)
* Update build scripts, update to Java 21, Add maven wrapper, add code coverage

* Fix up windows build

diff --git a/.github/workflows/check-pr.yaml b/.github/workflows/check-pr.yaml
--- a/.github/workflows/check-pr.yaml
+++ b/.github/workflows/check-pr.yaml
@@ -1,6 +1,13 @@
 name: Check PR
 on: pull_request
 
+permissions:
+    checks: write
+
+concurrency:
+  group: ${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
+
 jobs:
   maven:
     strategy:
@@ -9,9 +16,22 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
+      - uses: actions/setup-java@v4
         with:
-          distribution: temurin
-          java-version: 11
-      - name: Run Checks
-        run: mvn --batch-mode --no-transfer-progress --update-snapshots verify
+            distribution: 'temurin'
+            java-version: '21'
+            cache: 'maven'
+      - name: Compile
+        run: ./mvnw --batch-mode --no-transfer-progress --update-snapshots -T 4 package -DskipTests=true
+      - name: Tests and additional checks
+        run: ./mvnw --batch-mode --no-transfer-progress -T 4 verify -Ppackage
+      - name: Publish test report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/target/surefire-reports/TEST-*.xml"
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v3
+        if: matrix.os == 'ubuntu-latest'
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
